### ISSUE TITLE
Remove the Bind constructor of Program

### ISSUE THREAD

**Issue by lthms** [ANSSI-FR/FreeSpec#1]
Reading the definition of the `itree` monad from [*From C to Interaction Trees: Specifying, Verifying, and Testing a Networked Server*](https://arxiv.org/pdf/1811.11911.pdf) finally made me realize the `Bind` constructor is really not necessary.

I already had noticed it complicates the proofs (I needed a double induction on programs… not cool) and was searching for a custom induction scheme to prove, but the solution is actually way more simple than expected if we just remove `Bind` and define a custom function:

```coq
Inductive program ix a :=
| Ret: a -> program ix a
| Request {b}: ix b -> (b -> program ix a) -> program ix a .

Arguments Ret [ix a] _.
Arguments Request [ix a b] _ _.

Fixpoint bind
         {ix a b}
         (t:  program ix a)
         (f:  a -> program ix b)
  : program ix b :=
  match t with
  | Ret x => f x
  | Request e g => Request e (fun x => bind (g x) f)
  end.

Definition pure
           {ix a}
           (x:  a)
  : program ix a :=
  Ret x.

Definition lift
           {ix a}
           (e:  ix a)
  : program ix a :=
  Request e pure.

Notation "x <- p ; q" := (bind p (fun x => q)) (at level 100, right associativity, p at next level).
Notation "p ;; q" := (bind p (fun _ => q)) (at level 100, right associativity).

Inductive CONSOLE
  : Type -> Type :=
| Echo: nat -> CONSOLE unit
| Scan: CONSOLE nat.

Definition test
  : program CONSOLE nat :=
  x <- lift Scan ;
  y <- pure (S x) ;
  lift (Echo x) ;;
  pure y.

Eval compute in test.
(**
  = Request Scan (fun x : nat => Request (Echo x) (fun _ : unit => Ret (S x)))
  : program CONSOLE nat
**)
```

As the small example `test` suggests, the evaluation mechanism of Coq works really well to simplify the program.

**Comment by lthms** [comment]
Turns out, it is even more convenient than I initially thought!

```coq
Lemma bind_assoc
      {ix a b c}
      (p: program ix a)
      (f: a -> program ix b)
      (g: b -> program ix c)
  : bind (bind p f) g = bind p (fun x => bind (f x) g).
  induction p.
  + reflexivity.
  + cbn.
    match goal with
    | [ |- Request _ ?x = Request _ ?y ] => assert (Rw: x = y)
    end.
    ++ apply functional_extensionality.
       intros x.
       rewrite H.
       reflexivity.
    ++ now rewrite Rw.
Qed.
```

No more custom equivalence relation required.

**Comment by Lysxia** [comment]
:) I wondered whether that was intentional, since there is a nice symmetry in `Request : I A -> Program I A`.

**Comment by lthms** [comment]
The original definition of `Program` was extracted directly from the [`operational` package](https://hackage.haskell.org/package/operational). It’s interesting to notice that they also have a `ProgramView` datatype with two-constructors, but I never considered using it over `Program`.

____________________

This is beautiful.

```coq
Definition test
  : program CONSOLE nat :=
  x <- lift Scan ;
  y <- pure (S x) ;
  lift (Echo x) ;;
  pure y.

Definition test'
  : program CONSOLE nat :=
  x <- lift Scan ;
  lift (Echo x) ;;
  y <- pure (S x) ;
  pure y.

Goal test = test'.
  reflexivity.
Qed.
```
