### ISSUE TITLE
Should we use ExtLib in place of coq-prelude

### ISSUE THREAD

**Issue by lthms** [ANSSI-FR/FreeSpec#39]
It looks like `ExtLib` is becoming (was already?) the *de facto* standard to implement monads in Coq. Since we eventually target… well, Coq users, using the same tools looks like a good idea to favor adoption.

**Comment by lthms** [comment]
Feedback by Coq enthusiasts interested in FreeSpec is more than welcome, btw! Feel free to participate here if you have any input for us. :)

**Comment by Lysxia** [comment]
I don't think there's anything close to a consensus about ext-lib. It being taken into coq-community doesn't mean much.

**Comment by lthms** [comment]
Implemeted by #51; the reasoning is that implementing a prelude library like `coq-prelude` is hard, so it’s better if we do not reinvent the wheel here.

Thanks for the feedback @Lysxia and sorry for not reacting more quickly.
